
	premake.android = { "android" }
	local android = premake.android

	dofile("android.lua")

	newaction 
	{
		-- The trigger is what needs to be typed on the command line to cause 
		
		trigger = "android",
		
		-- The short name is used when this toolset name needs to be shown to
		-- the user, such as in status or error messages
		shortname = "android mk project",
		
		-- The description is shown in the help text (premake4 /help)
		description = "Generates android mk project (WIP)",

		-- Some actions imply a particular operating system: Visual Studio only
		-- runs on Windows, and Xcode only on Mac OS X. If this is the case,
		-- uncomment this line and set it to one of "windows", "linux" or "macosx".
		-- Otherwise, this action will target the current operating system.
		-- os = "macosx",

		-- Which kinds of targets this action supports; remove those you don't.
		valid_kinds = { "ConsoleApp", "WindowedApp", "SharedLib", "StaticLib" },

		-- Which programming languages this actions supports; remove those you don't.
		valid_languages = { "C", "C++", "Java" },

		-- Which compiler sets this action supports; remove those you don't. The set
		-- is specified with the /cc and /dotnet command-line options. You can find
		-- the tool interfaces at src/tools.
		valid_tools     = {
			cc     = { "gcc" },
		},

		-- This function is called during state validation. If your action has some
		-- special requirements you can check them here and error if necessary.
		
		
		oncheckproject = function(prj)
			-- if this_project_is_no_good(prj) then
			--    error("Project " .. prj.name .. " is no good", 0)
			-- end
		end,

		-- These functions will get called for each solution and project. The function
		-- premake.generate() creates a file for you in the correct place, taking into
		-- account any location information specified in the script. The sequence "%%"
		-- will be replaced by the solution/project name. The last parameter is the 
		-- function that will actually do the work of generating the file contents.

		--onsolution = function(sln)
		--	premake.generate(sln, "%%.sln.txt", premake.android.project )
		--end,
		

		onproject = function( prj )
        
            premake.make.mkdirRules( "res" )
			premake.make.mkdirRules( "libs" )
			premake.make.mkdirRules( "src" )
			premake.make.mkdirRules( "src/com" )
            
            premake.generate( prj, "build.xml", premake.android.buildxml )
			premake.generate( prj, "ant.properties", premake.android.antprop )
            premake.generate( prj, "project.properties", premake.android.projprop )
			--premake.generate( prj, "AndroidManifest.xml", premake.android.manifest )
			
            premake.generate( prj, "dummy", premake.android.project )
		end,

		-- These functions are called for each solution, project, and target as part
		-- of the "clean" action. They should remove any files generated by the tools.
		-- premake.clean.file() and premake.clean.directory() are convenience functions
		-- that use the same pattern matching as premake.generate() above.

		oncleansolution = function(sln)
			premake.clean.file(sln, "%%.sln.txt")
		end,
		
		oncleanproject  = function(prj)
			if premake.isdotnetproject(prj) then
				premake.clean.file(prj, "%%.csprj.txt")
			else
				premake.clean.file(prj, "%%.cprj.txt")
			end
		end,
		
		oncleantarget   = function(trg)
			-- 'trg' is the path and base name of the target being cleaned,
			-- like 'bin/debug/MyApplication'. So you might do something like:
			-- os.remove(trg .. ".exe")
		end,
	}

