#pragma once

#if defined Q_LINUX
#   define GL_FUN(x) x
#   define GL_FUN2(interf, x) x
#elif defined Q_RASPBERRY_PI
#   define GL_FUN(x) x
#   define GL_FUN2(interf, x) x
#else
#   define GL_FUN(x) this->m_funcs->_##x
#   define GL_FUN2(interf, x) interf->m_funcs->_##x
#endif

#if defined(Q_ANDROID)
//not defined in android!!!
typedef void (GL_APIENTRYP PFNGLTEXSTORAGE2DPROC) (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
#endif

namespace q
{
namespace video
{
namespace gles
{
	class GL_Ext_Functions
	{
	public:
#if defined(Q_WINDOWS)
		PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC _glRenderbufferStorageMultisample;
		PFNGLBLITFRAMEBUFFERPROC _glBlitFramebuffer;
		PFNGLCHECKFRAMEBUFFERSTATUSPROC _glCheckFramebufferStatus;
		PFNGLCLEARDEPTHFPROC _glClearDepthf;
		PFNGLCOMPRESSEDTEXIMAGE2DPROC _glCompressedTexImage2D;
		PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC _glCompressedTexSubImage2D;
		PFNGLBINDFRAMEBUFFERPROC _glBindFramebuffer;
		PFNGLBINDRENDERBUFFERPROC _glBindRenderbuffer;
		PFNGLACTIVETEXTUREPROC _glActiveTexture;
		PFNGLBLENDCOLORPROC _glBlendColor;
		PFNGLBLENDEQUATIONPROC _glBlendEquation;
		PFNGLBLENDFUNCSEPARATEPROC _glBlendFuncSeparate;
		PFNGLBINDBUFFERPROC _glBindBuffer;
		PFNGLBUFFERDATAPROC _glBufferData;
		PFNGLBUFFERSUBDATAPROC _glBufferSubData;
		PFNGLDELETEBUFFERSPROC _glDeleteBuffers;
		PFNGLGENBUFFERSPROC _glGenBuffers;
		PFNGLGETBUFFERPARAMETERIVPROC _glGetBufferParameteriv;
		PFNGLGETBUFFERPOINTERVPROC _glGetBufferPointerv;
		PFNGLGETBUFFERSUBDATAPROC _glGetBufferSubData;
		PFNGLISBUFFERPROC _glIsBuffer;
		PFNGLMAPBUFFERPROC _glMapBuffer;
		PFNGLUNMAPBUFFERPROC _glUnmapBuffer;
		PFNGLMAPBUFFERRANGEPROC _glMapBufferRange;
		PFNGLFLUSHMAPPEDBUFFERRANGEPROC _glFlushMappedBufferRange;
		PFNGLATTACHSHADERPROC _glAttachShader;
		PFNGLBINDATTRIBLOCATIONPROC _glBindAttribLocation;
		PFNGLBLENDEQUATIONSEPARATEPROC _glBlendEquationSeparate;
		PFNGLCOMPILESHADERPROC _glCompileShader;
		PFNGLCREATEPROGRAMPROC _glCreateProgram;
		PFNGLCREATESHADERPROC _glCreateShader;
		PFNGLDELETEPROGRAMPROC _glDeleteProgram;
		PFNGLDELETESHADERPROC _glDeleteShader;
		PFNGLDETACHSHADERPROC _glDetachShader;
		PFNGLDISABLEVERTEXATTRIBARRAYPROC _glDisableVertexAttribArray;
		PFNGLDRAWBUFFERSPROC _glDrawBuffers;
		PFNGLENABLEVERTEXATTRIBARRAYPROC _glEnableVertexAttribArray;
		PFNGLGETACTIVEATTRIBPROC _glGetActiveAttrib;
		PFNGLGETACTIVEUNIFORMPROC _glGetActiveUniform;
		PFNGLGETATTACHEDSHADERSPROC _glGetAttachedShaders;
		PFNGLGETATTRIBLOCATIONPROC _glGetAttribLocation;
		PFNGLGETPROGRAMINFOLOGPROC _glGetProgramInfoLog;
		PFNGLGETPROGRAMIVPROC _glGetProgramiv;
		PFNGLGETSHADERINFOLOGPROC _glGetShaderInfoLog;
		PFNGLGETSHADERSOURCEPROC _glGetShaderSource;
		PFNGLGETSHADERIVPROC _glGetShaderiv;
		PFNGLGETUNIFORMLOCATIONPROC _glGetUniformLocation;
		PFNGLGETUNIFORMFVPROC _glGetUniformfv;
		PFNGLGETUNIFORMIVPROC _glGetUniformiv;
		PFNGLGETVERTEXATTRIBPOINTERVPROC _glGetVertexAttribPointerv;
		PFNGLGETVERTEXATTRIBFVPROC _glGetVertexAttribfv;
		PFNGLGETVERTEXATTRIBIVPROC _glGetVertexAttribiv;
		PFNGLISPROGRAMPROC _glIsProgram;
		PFNGLISSHADERPROC _glIsShader;
		PFNGLLINKPROGRAMPROC _glLinkProgram;
		PFNGLSHADERSOURCEPROC _glShaderSource;
		PFNGLSTENCILFUNCSEPARATEPROC _glStencilFuncSeparate;
		PFNGLSTENCILMASKSEPARATEPROC _glStencilMaskSeparate;
		PFNGLSTENCILOPSEPARATEPROC _glStencilOpSeparate;
		PFNGLUNIFORM1FPROC _glUniform1f;
		PFNGLUNIFORM1FVPROC _glUniform1fv;
		PFNGLUNIFORM1IPROC _glUniform1i;
		PFNGLUNIFORM1IVPROC _glUniform1iv;
		PFNGLUNIFORM2FPROC _glUniform2f;
		PFNGLUNIFORM2FVPROC _glUniform2fv;
		PFNGLUNIFORM2IPROC _glUniform2i;
		PFNGLUNIFORM2IVPROC _glUniform2iv;
		PFNGLUNIFORM3FPROC _glUniform3f;
		PFNGLUNIFORM3FVPROC _glUniform3fv;
		PFNGLUNIFORM3IPROC _glUniform3i;
		PFNGLUNIFORM3IVPROC _glUniform3iv;
		PFNGLUNIFORM4FPROC _glUniform4f;
		PFNGLUNIFORM4FVPROC _glUniform4fv;
		PFNGLUNIFORM4IPROC _glUniform4i;
		PFNGLUNIFORM4IVPROC _glUniform4iv;
		PFNGLUNIFORMMATRIX2FVPROC _glUniformMatrix2fv;
		PFNGLUNIFORMMATRIX3FVPROC _glUniformMatrix3fv;
		PFNGLUNIFORMMATRIX4FVPROC _glUniformMatrix4fv;
		PFNGLUSEPROGRAMPROC _glUseProgram;
		PFNGLVALIDATEPROGRAMPROC _glValidateProgram;
		PFNGLVERTEXATTRIB1FPROC _glVertexAttrib1f;
		PFNGLVERTEXATTRIB1FVPROC _glVertexAttrib1fv;
		PFNGLVERTEXATTRIB2FPROC _glVertexAttrib2f;
		PFNGLVERTEXATTRIB2FVPROC _glVertexAttrib2fv;
		PFNGLVERTEXATTRIB3FPROC _glVertexAttrib3f;
		PFNGLVERTEXATTRIB3FVPROC _glVertexAttrib3fv;
		PFNGLVERTEXATTRIB4FPROC _glVertexAttrib4f;
		PFNGLVERTEXATTRIB4FVPROC _glVertexAttrib4fv;
		PFNGLVERTEXATTRIBPOINTERPROC _glVertexAttribPointer;
		PFNGLDELETEFRAMEBUFFERSPROC _glDeleteFramebuffers;
		PFNGLDELETERENDERBUFFERSPROC _glDeleteRenderbuffers;
		PFNGLDEPTHRANGEFPROC _glDepthRangef;
		PFNGLFRAMEBUFFERRENDERBUFFERPROC _glFramebufferRenderbuffer;
		PFNGLFRAMEBUFFERTEXTURE2DPROC _glFramebufferTexture2D;
		PFNGLGENERATEMIPMAPPROC _glGenerateMipmap;
		PFNGLGENFRAMEBUFFERSPROC _glGenFramebuffers;
		PFNGLGENRENDERBUFFERSPROC _glGenRenderbuffers;
		PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC _glGetFramebufferAttachmentParameteriv;
		PFNGLGETRENDERBUFFERPARAMETERIVPROC _glGetRenderbufferParameteriv;
		PFNGLGETSHADERPRECISIONFORMATPROC _glGetShaderPrecisionFormat;
		PFNGLISFRAMEBUFFERPROC _glIsFramebuffer;
		PFNGLISRENDERBUFFERPROC _glIsRenderbuffer;
		PFNGLRENDERBUFFERSTORAGEPROC _glRenderbufferStorage;
		PFNGLRELEASESHADERCOMPILERPROC _glReleaseShaderCompiler;
		PFNGLSAMPLECOVERAGEPROC _glSampleCoverage;
		PFNGLSHADERBINARYPROC _glShaderBinary;
		PFNGLBINDVERTEXARRAYPROC _glBindVertexArray;
		PFNGLDELETEVERTEXARRAYSPROC _glDeleteVertexArrays;
		PFNGLGENVERTEXARRAYSPROC _glGenVertexArrays;
		PFNGLISVERTEXARRAYPROC _glIsVertexArray;

		PFNGLGENQUERIESPROC _glGenQueries;
		PFNGLDELETEQUERIESPROC _glDeleteQueries;
		PFNGLISQUERYPROC _glIsQuery;
		PFNGLBEGINQUERYPROC _glBeginQuery;
		PFNGLENDQUERYPROC _glEndQuery;
		PFNGLGETQUERYIVPROC _glGetQueryiv;
		PFNGLGETQUERYOBJECTIVPROC _glGetQueryObjectiv;
		PFNGLGETQUERYOBJECTUIVPROC _glGetQueryObjectuiv;

		PFNGLTEXSTORAGE2DPROC _glTexStorage2D;


#elif defined (Q_ANDROID)
		PFNGLBINDVERTEXARRAYOESPROC _glBindVertexArray;
		PFNGLDELETEVERTEXARRAYSOESPROC _glDeleteVertexArrays;
		PFNGLGENVERTEXARRAYSOESPROC _glGenVertexArrays;
		PFNGLISVERTEXARRAYOESPROC _glIsVertexArray;
		PFNGLTEXSTORAGE2DPROC _glTexStorage2D;
#endif
	};
}
}
}
